# create-users/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: create-users
  template:
    metadata:
      labels:
        app: create-users
    spec:
      containers:
        - name: create-users
          image: myrepo/create-users:latest
          ports:
            - containerPort: 8082
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@db:5432/mydb?sslmode=disable"
