# retrieve-users/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieve-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrieve-users
  template:
    metadata:
      labels:
        app: retrieve-users
    spec:
      containers:
        - name: retrieve-users
          image: myrepo/retrieve-users:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@db:5432/mydb?sslmode=disable"
